spring.application.name=TodoAppJWT
spring.datasource.url=jdbc:postgresql://localhost:5433/TodoJWT
spring.datasource.username=postgres
spring.datasource.password=1111
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true